apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../psp

images:
  - name: quay.io/minio/directpv
    digest: sha256:98c23183f3abb8d9b6e0c300677605cc822e039fc81ce0e5dd8bef1006547627

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.0.16
    target:
      kind: Deployment
      name: controller
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.0.16
    target:
      kind: DaemonSet
      name: node-server
