linters-settings:
run:
  go: "1.22"

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - gofmt
    - unconvert
    - unused
    - gocritic
    - gofumpt
    - tenv
    - durationcheck

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - exitAfterDefer

service:
  golangci-lint-version: 1.59.1 # use the fixed version to not introduce new linters unexpectedly
