linters-settings:
run:
  go: "1.23"

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - gofmt
    - unconvert
    - unused
    - gocritic
    - gofumpt
    - tenv
    - durationcheck
    - staticcheck

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    - exitAfterDefer
    - redefines-builtin-id

service:
  golangci-lint-version: 1.62.0 # use the fixed version to not introduce new linters unexpectedly
