linters-settings:
  misspell:
    locale: US

run:
  go: "1.24"

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - gofmt
    - unconvert
    - unused
    - gocritic
    - gofumpt
    - usetesting
    - durationcheck
    - staticcheck

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    - exitAfterDefer
    - redefines-builtin-id
