sudo: required
dist: focal
env:
  global:
    - GO111MODULE=on
addons:
  apt:
    packages:
      - qemu
      - qemu-kvm
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - libguestfs-tools
      - dnsmasq
language: go
go:
  - 1.17.x
script: ./travis-deploy.sh
