FROM registry.access.redhat.com/ubi7/ubi-minimal:7.9

WORKDIR /

RUN microdnf update --nodocs

COPY centos7.repo /etc/yum.repos.d/CentOS.repo

RUN \
    curl -L https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7 -o /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && \
    microdnf install xfsprogs --nodocs && \
    microdnf clean all && \
    rm -f /etc/yum.repos.d/CentOS.repo

COPY direct-csi /direct-csi
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

ENTRYPOINT ["/direct-csi"]
