kind: Service
apiVersion: v1
metadata:
  name: direct-csi-driver-test-app-svc
  labels:
    app: job-csi-driver-test-app
spec:
  selector:
    app: job-csi-driver-test-app
  ports:
    - name: unused
      port: 12345

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: job-csi-driver-test-app
  labels:
    app: job-csi-driver-test-app
spec:
  serviceName: "direct-csi-driver-test-app-svc"
  replicas: 112 # 4 volumes per drive; assuming 7 nodes in cluster
  selector:
    matchLabels:
      app: job-csi-driver-test-app
  template:
    metadata:
      labels:
        app: job-csi-driver-test-app
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        volumeMounts:
        - name: direct-csi-driver-min-io-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # This is the specification in which you reference the StorageClass
  - metadata:
      name: direct-csi-driver-min-io-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi        
      storageClassName: direct.csi.driver.min.io # This field references the existing StorageClass
