apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml
  - directpvdrives.directpv.min.io.yaml
  - directpvinitrequests.directpv.min.io.yaml
  - directpvnodes.directpv.min.io.yaml
  - directpvvolumes.directpv.min.io.yaml
  - CSIDriver.yaml
  - StorageClass.yaml
  - ServiceAccount.yaml
  - ClusterRole.yaml
  - ClusterRoleBinding.yaml
  - Role.yaml
  - RoleBinding.yaml
  - DaemonSet.yaml
  - Deployment.yaml

images:
  - name: quay.io/minio/directpv
    digest: sha256:352806476d3962a6fc4b8a615c95ce2391ca8b0ece00c99b402fd140555b69b5

  - name: quay.io/minio/csi-node-driver-registrar
    digest: sha256:183b3ac969d133457595fa2abfd9d81d20e83a6bc4606375662d036f56462dde

  - name: quay.io/minio/livenessprobe
    digest: sha256:af8bac7b24bbfcc064e58d45c1c2ebaf75b9ac71315a604e0870100fa6aed8da

  - name: quay.io/minio/csi-provisioner
    digest: sha256:f83e880ce4290b1ef4fa15a588138eafecdb40106208a5295c0b24d03cbaddbd

  - name: quay.io/minio/csi-resizer
    digest: sha256:cb338f5c5a9f781f289b6f25fedebbeeb4eec9fda2aeb2c0a1eaa8529c4c9738

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.1.5
    target:
      kind: Deployment
      name: controller
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v4.1.5
    target:
      kind: DaemonSet
      name: node-server
