// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StorageTopologyLister helps list StorageTopologies.
type StorageTopologyLister interface {
	// List lists all StorageTopologies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.StorageTopology, err error)
	// Get retrieves the StorageTopology from the index for a given name.
	Get(name string) (*v1alpha1.StorageTopology, error)
	StorageTopologyListerExpansion
}

// storageTopologyLister implements the StorageTopologyLister interface.
type storageTopologyLister struct {
	indexer cache.Indexer
}

// NewStorageTopologyLister returns a new StorageTopologyLister.
func NewStorageTopologyLister(indexer cache.Indexer) StorageTopologyLister {
	return &storageTopologyLister{indexer: indexer}
}

// List lists all StorageTopologies in the indexer.
func (s *storageTopologyLister) List(selector labels.Selector) (ret []*v1alpha1.StorageTopology, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StorageTopology))
	})
	return ret, err
}

// Get retrieves the StorageTopology from the index for a given name.
func (s *storageTopologyLister) Get(name string) (*v1alpha1.StorageTopology, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("storagetopology"), name)
	}
	return obj.(*v1alpha1.StorageTopology), nil
}
