/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageTopologies implements StorageTopologyInterface
type FakeStorageTopologies struct {
	Fake *FakeDirectV1alpha1
}

var storagetopologiesResource = schema.GroupVersionResource{Group: "direct.csi.min.io", Version: "v1alpha1", Resource: "storagetopologies"}

var storagetopologiesKind = schema.GroupVersionKind{Group: "direct.csi.min.io", Version: "v1alpha1", Kind: "StorageTopology"}

// Get takes name of the storageTopology, and returns the corresponding storageTopology object, and an error if there is any.
func (c *FakeStorageTopologies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(storagetopologiesResource, name), &v1alpha1.StorageTopology{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// List takes label and field selectors, and returns the list of StorageTopologies that match those selectors.
func (c *FakeStorageTopologies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(storagetopologiesResource, storagetopologiesKind, opts), &v1alpha1.StorageTopologyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StorageTopologyList{ListMeta: obj.(*v1alpha1.StorageTopologyList).ListMeta}
	for _, item := range obj.(*v1alpha1.StorageTopologyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageTopologies.
func (c *FakeStorageTopologies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(storagetopologiesResource, opts))
}

// Create takes the representation of a storageTopology and creates it.  Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *FakeStorageTopologies) Create(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.CreateOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(storagetopologiesResource, storageTopology), &v1alpha1.StorageTopology{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// Update takes the representation of a storageTopology and updates it. Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *FakeStorageTopologies) Update(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(storagetopologiesResource, storageTopology), &v1alpha1.StorageTopology{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// Delete takes name of the storageTopology and deletes it. Returns an error if one occurs.
func (c *FakeStorageTopologies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(storagetopologiesResource, name), &v1alpha1.StorageTopology{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageTopologies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(storagetopologiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageTopologyList{})
	return err
}

// Patch applies the patch and returns the patched storageTopology.
func (c *FakeStorageTopologies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(storagetopologiesResource, name, pt, data, subresources...), &v1alpha1.StorageTopology{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}
