/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageTopologyLists implements StorageTopologyListInterface
type FakeStorageTopologyLists struct {
	Fake *FakeDirectV1alpha1
}

var storagetopologylistsResource = schema.GroupVersionResource{Group: "direct.csi.min.io", Version: "v1alpha1", Resource: "storagetopologylists"}

var storagetopologylistsKind = schema.GroupVersionKind{Group: "direct.csi.min.io", Version: "v1alpha1", Kind: "StorageTopologyList"}

// Get takes name of the storageTopologyList, and returns the corresponding storageTopologyList object, and an error if there is any.
func (c *FakeStorageTopologyLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(storagetopologylistsResource, name), &v1alpha1.StorageTopologyList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopologyList), err
}

// List takes label and field selectors, and returns the list of StorageTopologyLists that match those selectors.
func (c *FakeStorageTopologyLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageTopologyListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(storagetopologylistsResource, storagetopologylistsKind, opts), &v1alpha1.StorageTopologyListList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopologyListList), err
}

// Watch returns a watch.Interface that watches the requested storageTopologyLists.
func (c *FakeStorageTopologyLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(storagetopologylistsResource, opts))
}

// Create takes the representation of a storageTopologyList and creates it.  Returns the server's representation of the storageTopologyList, and an error, if there is any.
func (c *FakeStorageTopologyLists) Create(ctx context.Context, storageTopologyList *v1alpha1.StorageTopologyList, opts v1.CreateOptions) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(storagetopologylistsResource, storageTopologyList), &v1alpha1.StorageTopologyList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopologyList), err
}

// Update takes the representation of a storageTopologyList and updates it. Returns the server's representation of the storageTopologyList, and an error, if there is any.
func (c *FakeStorageTopologyLists) Update(ctx context.Context, storageTopologyList *v1alpha1.StorageTopologyList, opts v1.UpdateOptions) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(storagetopologylistsResource, storageTopologyList), &v1alpha1.StorageTopologyList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopologyList), err
}

// Delete takes name of the storageTopologyList and deletes it. Returns an error if one occurs.
func (c *FakeStorageTopologyLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(storagetopologylistsResource, name), &v1alpha1.StorageTopologyList{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageTopologyLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(storagetopologylistsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageTopologyListList{})
	return err
}

// Patch applies the patch and returns the patched storageTopologyList.
func (c *FakeStorageTopologyLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(storagetopologylistsResource, name, pt, data, subresources...), &v1alpha1.StorageTopologyList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopologyList), err
}
