/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDirectCSIDrives implements DirectCSIDriveInterface
type FakeDirectCSIDrives struct {
	Fake *FakeDirectV1alpha1
}

var directcsidrivesResource = schema.GroupVersionResource{Group: "direct.csi.min.io", Version: "v1alpha1", Resource: "directcsidrives"}

var directcsidrivesKind = schema.GroupVersionKind{Group: "direct.csi.min.io", Version: "v1alpha1", Kind: "DirectCSIDrive"}

// Get takes name of the directCSIDrive, and returns the corresponding directCSIDrive object, and an error if there is any.
func (c *FakeDirectCSIDrives) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DirectCSIDrive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(directcsidrivesResource, name), &v1alpha1.DirectCSIDrive{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DirectCSIDrive), err
}

// List takes label and field selectors, and returns the list of DirectCSIDrives that match those selectors.
func (c *FakeDirectCSIDrives) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DirectCSIDriveList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(directcsidrivesResource, directcsidrivesKind, opts), &v1alpha1.DirectCSIDriveList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DirectCSIDriveList{ListMeta: obj.(*v1alpha1.DirectCSIDriveList).ListMeta}
	for _, item := range obj.(*v1alpha1.DirectCSIDriveList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested directCSIDrives.
func (c *FakeDirectCSIDrives) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(directcsidrivesResource, opts))
}

// Create takes the representation of a directCSIDrive and creates it.  Returns the server's representation of the directCSIDrive, and an error, if there is any.
func (c *FakeDirectCSIDrives) Create(ctx context.Context, directCSIDrive *v1alpha1.DirectCSIDrive, opts v1.CreateOptions) (result *v1alpha1.DirectCSIDrive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(directcsidrivesResource, directCSIDrive), &v1alpha1.DirectCSIDrive{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DirectCSIDrive), err
}

// Update takes the representation of a directCSIDrive and updates it. Returns the server's representation of the directCSIDrive, and an error, if there is any.
func (c *FakeDirectCSIDrives) Update(ctx context.Context, directCSIDrive *v1alpha1.DirectCSIDrive, opts v1.UpdateOptions) (result *v1alpha1.DirectCSIDrive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(directcsidrivesResource, directCSIDrive), &v1alpha1.DirectCSIDrive{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DirectCSIDrive), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDirectCSIDrives) UpdateStatus(ctx context.Context, directCSIDrive *v1alpha1.DirectCSIDrive, opts v1.UpdateOptions) (*v1alpha1.DirectCSIDrive, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(directcsidrivesResource, "status", directCSIDrive), &v1alpha1.DirectCSIDrive{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DirectCSIDrive), err
}

// Delete takes name of the directCSIDrive and deletes it. Returns an error if one occurs.
func (c *FakeDirectCSIDrives) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(directcsidrivesResource, name), &v1alpha1.DirectCSIDrive{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDirectCSIDrives) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(directcsidrivesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DirectCSIDriveList{})
	return err
}

// Patch applies the patch and returns the patched directCSIDrive.
func (c *FakeDirectCSIDrives) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DirectCSIDrive, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(directcsidrivesResource, name, pt, data, subresources...), &v1alpha1.DirectCSIDrive{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DirectCSIDrive), err
}
