apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for charts.quay.io/v1alpha1, Kind: DirectPVChart
##
- apiGroups:
  - charts.quay.io
  resources:
  - directpvcharts
  - directpvcharts/status
  - directpvcharts/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "namespaces"
- verbs:
  - "*"
  apiGroups:
  - "storage.k8s.io"
  resources:
  - "csidrivers"
  - "storageclasses"
- verbs:
  - "*"
  apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  - "deployments"

#+kubebuilder:scaffold:rules
