//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This file is part of MinIO DirectPV
// Copyright (c) 2021, 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta5

import (
	unsafe "unsafe"

	v1beta4 "github.com/minio/directpv/pkg/legacy/apis/direct.csi.min.io/v1beta4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DirectCSIDrive)(nil), (*v1beta4.DirectCSIDrive)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive(a.(*DirectCSIDrive), b.(*v1beta4.DirectCSIDrive), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIDrive)(nil), (*DirectCSIDrive)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive(a.(*v1beta4.DirectCSIDrive), b.(*DirectCSIDrive), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIDriveList)(nil), (*v1beta4.DirectCSIDriveList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIDriveList_To_v1beta4_DirectCSIDriveList(a.(*DirectCSIDriveList), b.(*v1beta4.DirectCSIDriveList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIDriveList)(nil), (*DirectCSIDriveList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIDriveList_To_v1beta5_DirectCSIDriveList(a.(*v1beta4.DirectCSIDriveList), b.(*DirectCSIDriveList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIDriveSpec)(nil), (*v1beta4.DirectCSIDriveSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec(a.(*DirectCSIDriveSpec), b.(*v1beta4.DirectCSIDriveSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIDriveSpec)(nil), (*DirectCSIDriveSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec(a.(*v1beta4.DirectCSIDriveSpec), b.(*DirectCSIDriveSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIDriveStatus)(nil), (*v1beta4.DirectCSIDriveStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus(a.(*DirectCSIDriveStatus), b.(*v1beta4.DirectCSIDriveStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIDriveStatus)(nil), (*DirectCSIDriveStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus(a.(*v1beta4.DirectCSIDriveStatus), b.(*DirectCSIDriveStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIVolume)(nil), (*v1beta4.DirectCSIVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIVolume_To_v1beta4_DirectCSIVolume(a.(*DirectCSIVolume), b.(*v1beta4.DirectCSIVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIVolume)(nil), (*DirectCSIVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIVolume_To_v1beta5_DirectCSIVolume(a.(*v1beta4.DirectCSIVolume), b.(*DirectCSIVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIVolumeList)(nil), (*v1beta4.DirectCSIVolumeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIVolumeList_To_v1beta4_DirectCSIVolumeList(a.(*DirectCSIVolumeList), b.(*v1beta4.DirectCSIVolumeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIVolumeList)(nil), (*DirectCSIVolumeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIVolumeList_To_v1beta5_DirectCSIVolumeList(a.(*v1beta4.DirectCSIVolumeList), b.(*DirectCSIVolumeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DirectCSIVolumeStatus)(nil), (*v1beta4.DirectCSIVolumeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus(a.(*DirectCSIVolumeStatus), b.(*v1beta4.DirectCSIVolumeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.DirectCSIVolumeStatus)(nil), (*DirectCSIVolumeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus(a.(*v1beta4.DirectCSIVolumeStatus), b.(*DirectCSIVolumeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OtherMountsInfo)(nil), (*v1beta4.OtherMountsInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_OtherMountsInfo_To_v1beta4_OtherMountsInfo(a.(*OtherMountsInfo), b.(*v1beta4.OtherMountsInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.OtherMountsInfo)(nil), (*OtherMountsInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_OtherMountsInfo_To_v1beta5_OtherMountsInfo(a.(*v1beta4.OtherMountsInfo), b.(*OtherMountsInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RequestedFormat)(nil), (*v1beta4.RequestedFormat)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta5_RequestedFormat_To_v1beta4_RequestedFormat(a.(*RequestedFormat), b.(*v1beta4.RequestedFormat), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta4.RequestedFormat)(nil), (*RequestedFormat)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta4_RequestedFormat_To_v1beta5_RequestedFormat(a.(*v1beta4.RequestedFormat), b.(*RequestedFormat), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive(in *DirectCSIDrive, out *v1beta4.DirectCSIDrive, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive(in *DirectCSIDrive, out *v1beta4.DirectCSIDrive, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive(in, out, s)
}

func autoConvert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive(in *v1beta4.DirectCSIDrive, out *DirectCSIDrive, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive(in *v1beta4.DirectCSIDrive, out *DirectCSIDrive, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive(in, out, s)
}

func autoConvert_v1beta5_DirectCSIDriveList_To_v1beta4_DirectCSIDriveList(in *DirectCSIDriveList, out *v1beta4.DirectCSIDriveList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta4.DirectCSIDrive, len(*in))
		for i := range *in {
			if err := Convert_v1beta5_DirectCSIDrive_To_v1beta4_DirectCSIDrive(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta5_DirectCSIDriveList_To_v1beta4_DirectCSIDriveList is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIDriveList_To_v1beta4_DirectCSIDriveList(in *DirectCSIDriveList, out *v1beta4.DirectCSIDriveList, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIDriveList_To_v1beta4_DirectCSIDriveList(in, out, s)
}

func autoConvert_v1beta4_DirectCSIDriveList_To_v1beta5_DirectCSIDriveList(in *v1beta4.DirectCSIDriveList, out *DirectCSIDriveList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DirectCSIDrive, len(*in))
		for i := range *in {
			if err := Convert_v1beta4_DirectCSIDrive_To_v1beta5_DirectCSIDrive(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta4_DirectCSIDriveList_To_v1beta5_DirectCSIDriveList is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIDriveList_To_v1beta5_DirectCSIDriveList(in *v1beta4.DirectCSIDriveList, out *DirectCSIDriveList, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIDriveList_To_v1beta5_DirectCSIDriveList(in, out, s)
}

func autoConvert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec(in *DirectCSIDriveSpec, out *v1beta4.DirectCSIDriveSpec, s conversion.Scope) error {
	out.RequestedFormat = (*v1beta4.RequestedFormat)(unsafe.Pointer(in.RequestedFormat))
	out.DirectCSIOwned = in.DirectCSIOwned
	out.DriveTaint = *(*map[string]string)(unsafe.Pointer(&in.DriveTaint))
	return nil
}

// Convert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec(in *DirectCSIDriveSpec, out *v1beta4.DirectCSIDriveSpec, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIDriveSpec_To_v1beta4_DirectCSIDriveSpec(in, out, s)
}

func autoConvert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec(in *v1beta4.DirectCSIDriveSpec, out *DirectCSIDriveSpec, s conversion.Scope) error {
	out.RequestedFormat = (*RequestedFormat)(unsafe.Pointer(in.RequestedFormat))
	out.DirectCSIOwned = in.DirectCSIOwned
	out.DriveTaint = *(*map[string]string)(unsafe.Pointer(&in.DriveTaint))
	return nil
}

// Convert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec(in *v1beta4.DirectCSIDriveSpec, out *DirectCSIDriveSpec, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIDriveSpec_To_v1beta5_DirectCSIDriveSpec(in, out, s)
}

func autoConvert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus(in *DirectCSIDriveStatus, out *v1beta4.DirectCSIDriveStatus, s conversion.Scope) error {
	out.Path = in.Path
	out.AllocatedCapacity = in.AllocatedCapacity
	out.FreeCapacity = in.FreeCapacity
	out.RootPartition = in.RootPartition
	out.PartitionNum = in.PartitionNum
	out.Filesystem = in.Filesystem
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	out.NodeName = in.NodeName
	out.DriveStatus = v1beta4.DriveStatus(in.DriveStatus)
	out.ModelNumber = in.ModelNumber
	out.SerialNumber = in.SerialNumber
	out.TotalCapacity = in.TotalCapacity
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.LogicalBlockSize = in.LogicalBlockSize
	out.Topology = *(*map[string]string)(unsafe.Pointer(&in.Topology))
	out.AccessTier = v1beta4.AccessTier(in.AccessTier)
	out.FilesystemUUID = in.FilesystemUUID
	out.PartitionUUID = in.PartitionUUID
	out.MajorNumber = in.MajorNumber
	out.MinorNumber = in.MinorNumber
	out.UeventSerial = in.UeventSerial
	out.UeventFSUUID = in.UeventFSUUID
	out.WWID = in.WWID
	// INFO: in.WWIDWithExtension opted out of conversion generation
	out.Vendor = in.Vendor
	out.DMName = in.DMName
	out.DMUUID = in.DMUUID
	out.MDUUID = in.MDUUID
	out.PartTableUUID = in.PartTableUUID
	out.PartTableType = in.PartTableType
	out.Virtual = in.Virtual
	out.ReadOnly = in.ReadOnly
	out.Partitioned = in.Partitioned
	out.SwapOn = in.SwapOn
	out.Master = in.Master
	out.OtherMountsInfo = *(*[]v1beta4.OtherMountsInfo)(unsafe.Pointer(&in.OtherMountsInfo))
	out.PCIPath = in.PCIPath
	out.SerialNumberLong = in.SerialNumberLong
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus(in *DirectCSIDriveStatus, out *v1beta4.DirectCSIDriveStatus, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIDriveStatus_To_v1beta4_DirectCSIDriveStatus(in, out, s)
}

func autoConvert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus(in *v1beta4.DirectCSIDriveStatus, out *DirectCSIDriveStatus, s conversion.Scope) error {
	out.Path = in.Path
	out.AllocatedCapacity = in.AllocatedCapacity
	out.FreeCapacity = in.FreeCapacity
	out.RootPartition = in.RootPartition
	out.PartitionNum = in.PartitionNum
	out.Filesystem = in.Filesystem
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	out.NodeName = in.NodeName
	out.DriveStatus = DriveStatus(in.DriveStatus)
	out.ModelNumber = in.ModelNumber
	out.SerialNumber = in.SerialNumber
	out.TotalCapacity = in.TotalCapacity
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.LogicalBlockSize = in.LogicalBlockSize
	out.Topology = *(*map[string]string)(unsafe.Pointer(&in.Topology))
	out.AccessTier = AccessTier(in.AccessTier)
	out.FilesystemUUID = in.FilesystemUUID
	out.PartitionUUID = in.PartitionUUID
	out.MajorNumber = in.MajorNumber
	out.MinorNumber = in.MinorNumber
	out.UeventSerial = in.UeventSerial
	out.UeventFSUUID = in.UeventFSUUID
	out.WWID = in.WWID
	out.Vendor = in.Vendor
	out.DMName = in.DMName
	out.DMUUID = in.DMUUID
	out.MDUUID = in.MDUUID
	out.PartTableUUID = in.PartTableUUID
	out.PartTableType = in.PartTableType
	out.Virtual = in.Virtual
	out.ReadOnly = in.ReadOnly
	out.Partitioned = in.Partitioned
	out.SwapOn = in.SwapOn
	out.Master = in.Master
	out.OtherMountsInfo = *(*[]OtherMountsInfo)(unsafe.Pointer(&in.OtherMountsInfo))
	out.PCIPath = in.PCIPath
	out.SerialNumberLong = in.SerialNumberLong
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus(in *v1beta4.DirectCSIDriveStatus, out *DirectCSIDriveStatus, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIDriveStatus_To_v1beta5_DirectCSIDriveStatus(in, out, s)
}

func autoConvert_v1beta5_DirectCSIVolume_To_v1beta4_DirectCSIVolume(in *DirectCSIVolume, out *v1beta4.DirectCSIVolume, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta5_DirectCSIVolume_To_v1beta4_DirectCSIVolume is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIVolume_To_v1beta4_DirectCSIVolume(in *DirectCSIVolume, out *v1beta4.DirectCSIVolume, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIVolume_To_v1beta4_DirectCSIVolume(in, out, s)
}

func autoConvert_v1beta4_DirectCSIVolume_To_v1beta5_DirectCSIVolume(in *v1beta4.DirectCSIVolume, out *DirectCSIVolume, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta4_DirectCSIVolume_To_v1beta5_DirectCSIVolume is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIVolume_To_v1beta5_DirectCSIVolume(in *v1beta4.DirectCSIVolume, out *DirectCSIVolume, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIVolume_To_v1beta5_DirectCSIVolume(in, out, s)
}

func autoConvert_v1beta5_DirectCSIVolumeList_To_v1beta4_DirectCSIVolumeList(in *DirectCSIVolumeList, out *v1beta4.DirectCSIVolumeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta4.DirectCSIVolume)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta5_DirectCSIVolumeList_To_v1beta4_DirectCSIVolumeList is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIVolumeList_To_v1beta4_DirectCSIVolumeList(in *DirectCSIVolumeList, out *v1beta4.DirectCSIVolumeList, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIVolumeList_To_v1beta4_DirectCSIVolumeList(in, out, s)
}

func autoConvert_v1beta4_DirectCSIVolumeList_To_v1beta5_DirectCSIVolumeList(in *v1beta4.DirectCSIVolumeList, out *DirectCSIVolumeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DirectCSIVolume)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta4_DirectCSIVolumeList_To_v1beta5_DirectCSIVolumeList is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIVolumeList_To_v1beta5_DirectCSIVolumeList(in *v1beta4.DirectCSIVolumeList, out *DirectCSIVolumeList, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIVolumeList_To_v1beta5_DirectCSIVolumeList(in, out, s)
}

func autoConvert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus(in *DirectCSIVolumeStatus, out *v1beta4.DirectCSIVolumeStatus, s conversion.Scope) error {
	out.Drive = in.Drive
	out.NodeName = in.NodeName
	out.HostPath = in.HostPath
	out.StagingPath = in.StagingPath
	out.ContainerPath = in.ContainerPath
	out.TotalCapacity = in.TotalCapacity
	out.AvailableCapacity = in.AvailableCapacity
	out.UsedCapacity = in.UsedCapacity
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus is an autogenerated conversion function.
func Convert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus(in *DirectCSIVolumeStatus, out *v1beta4.DirectCSIVolumeStatus, s conversion.Scope) error {
	return autoConvert_v1beta5_DirectCSIVolumeStatus_To_v1beta4_DirectCSIVolumeStatus(in, out, s)
}

func autoConvert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus(in *v1beta4.DirectCSIVolumeStatus, out *DirectCSIVolumeStatus, s conversion.Scope) error {
	out.Drive = in.Drive
	out.NodeName = in.NodeName
	out.HostPath = in.HostPath
	out.StagingPath = in.StagingPath
	out.ContainerPath = in.ContainerPath
	out.TotalCapacity = in.TotalCapacity
	out.AvailableCapacity = in.AvailableCapacity
	out.UsedCapacity = in.UsedCapacity
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus is an autogenerated conversion function.
func Convert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus(in *v1beta4.DirectCSIVolumeStatus, out *DirectCSIVolumeStatus, s conversion.Scope) error {
	return autoConvert_v1beta4_DirectCSIVolumeStatus_To_v1beta5_DirectCSIVolumeStatus(in, out, s)
}

func autoConvert_v1beta5_OtherMountsInfo_To_v1beta4_OtherMountsInfo(in *OtherMountsInfo, out *v1beta4.OtherMountsInfo, s conversion.Scope) error {
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	return nil
}

// Convert_v1beta5_OtherMountsInfo_To_v1beta4_OtherMountsInfo is an autogenerated conversion function.
func Convert_v1beta5_OtherMountsInfo_To_v1beta4_OtherMountsInfo(in *OtherMountsInfo, out *v1beta4.OtherMountsInfo, s conversion.Scope) error {
	return autoConvert_v1beta5_OtherMountsInfo_To_v1beta4_OtherMountsInfo(in, out, s)
}

func autoConvert_v1beta4_OtherMountsInfo_To_v1beta5_OtherMountsInfo(in *v1beta4.OtherMountsInfo, out *OtherMountsInfo, s conversion.Scope) error {
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	return nil
}

// Convert_v1beta4_OtherMountsInfo_To_v1beta5_OtherMountsInfo is an autogenerated conversion function.
func Convert_v1beta4_OtherMountsInfo_To_v1beta5_OtherMountsInfo(in *v1beta4.OtherMountsInfo, out *OtherMountsInfo, s conversion.Scope) error {
	return autoConvert_v1beta4_OtherMountsInfo_To_v1beta5_OtherMountsInfo(in, out, s)
}

func autoConvert_v1beta5_RequestedFormat_To_v1beta4_RequestedFormat(in *RequestedFormat, out *v1beta4.RequestedFormat, s conversion.Scope) error {
	out.Force = in.Force
	out.Purge = in.Purge
	out.Filesystem = in.Filesystem
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	return nil
}

// Convert_v1beta5_RequestedFormat_To_v1beta4_RequestedFormat is an autogenerated conversion function.
func Convert_v1beta5_RequestedFormat_To_v1beta4_RequestedFormat(in *RequestedFormat, out *v1beta4.RequestedFormat, s conversion.Scope) error {
	return autoConvert_v1beta5_RequestedFormat_To_v1beta4_RequestedFormat(in, out, s)
}

func autoConvert_v1beta4_RequestedFormat_To_v1beta5_RequestedFormat(in *v1beta4.RequestedFormat, out *RequestedFormat, s conversion.Scope) error {
	out.Force = in.Force
	out.Purge = in.Purge
	out.Filesystem = in.Filesystem
	out.Mountpoint = in.Mountpoint
	out.MountOptions = *(*[]string)(unsafe.Pointer(&in.MountOptions))
	return nil
}

// Convert_v1beta4_RequestedFormat_To_v1beta5_RequestedFormat is an autogenerated conversion function.
func Convert_v1beta4_RequestedFormat_To_v1beta5_RequestedFormat(in *v1beta4.RequestedFormat, out *RequestedFormat, s conversion.Scope) error {
	return autoConvert_v1beta4_RequestedFormat_To_v1beta5_RequestedFormat(in, out, s)
}
