// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageTopologies implements StorageTopologyInterface
type FakeStorageTopologies struct {
	Fake *FakeDirectV1alpha1
	ns   string
}

var storagetopologiesResource = schema.GroupVersionResource{Group: "direct.csi.min.io", Version: "v1alpha1", Resource: "storagetopologies"}

var storagetopologiesKind = schema.GroupVersionKind{Group: "direct.csi.min.io", Version: "v1alpha1", Kind: "StorageTopology"}

// Get takes name of the storageTopology, and returns the corresponding storageTopology object, and an error if there is any.
func (c *FakeStorageTopologies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagetopologiesResource, c.ns, name), &v1alpha1.StorageTopology{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// List takes label and field selectors, and returns the list of StorageTopologies that match those selectors.
func (c *FakeStorageTopologies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageTopologyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagetopologiesResource, storagetopologiesKind, c.ns, opts), &v1alpha1.StorageTopologyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StorageTopologyList{ListMeta: obj.(*v1alpha1.StorageTopologyList).ListMeta}
	for _, item := range obj.(*v1alpha1.StorageTopologyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageTopologies.
func (c *FakeStorageTopologies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagetopologiesResource, c.ns, opts))

}

// Create takes the representation of a storageTopology and creates it.  Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *FakeStorageTopologies) Create(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.CreateOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagetopologiesResource, c.ns, storageTopology), &v1alpha1.StorageTopology{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// Update takes the representation of a storageTopology and updates it. Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *FakeStorageTopologies) Update(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagetopologiesResource, c.ns, storageTopology), &v1alpha1.StorageTopology{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStorageTopologies) UpdateStatus(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (*v1alpha1.StorageTopology, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(storagetopologiesResource, "status", c.ns, storageTopology), &v1alpha1.StorageTopology{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}

// Delete takes name of the storageTopology and deletes it. Returns an error if one occurs.
func (c *FakeStorageTopologies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagetopologiesResource, c.ns, name), &v1alpha1.StorageTopology{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageTopologies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagetopologiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageTopologyList{})
	return err
}

// Patch applies the patch and returns the patched storageTopology.
func (c *FakeStorageTopologies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageTopology, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagetopologiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.StorageTopology{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageTopology), err
}
