// This file is part of MinIO DirectPV
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/minio/directpv/pkg/apis/directpv.min.io/v1beta1"
	directpvminiov1beta1 "github.com/minio/directpv/pkg/clientset/typed/directpv.min.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDirectPVDrives implements DirectPVDriveInterface
type fakeDirectPVDrives struct {
	*gentype.FakeClientWithList[*v1beta1.DirectPVDrive, *v1beta1.DirectPVDriveList]
	Fake *FakeDirectpvV1beta1
}

func newFakeDirectPVDrives(fake *FakeDirectpvV1beta1) directpvminiov1beta1.DirectPVDriveInterface {
	return &fakeDirectPVDrives{
		gentype.NewFakeClientWithList[*v1beta1.DirectPVDrive, *v1beta1.DirectPVDriveList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("directpvdrives"),
			v1beta1.SchemeGroupVersion.WithKind("DirectPVDrive"),
			func() *v1beta1.DirectPVDrive { return &v1beta1.DirectPVDrive{} },
			func() *v1beta1.DirectPVDriveList { return &v1beta1.DirectPVDriveList{} },
			func(dst, src *v1beta1.DirectPVDriveList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.DirectPVDriveList) []*v1beta1.DirectPVDrive {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.DirectPVDriveList, items []*v1beta1.DirectPVDrive) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
