// This file is part of MinIO DirectPV
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/minio/directpv/pkg/clientset/typed/directpv.min.io/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDirectpvV1beta1 struct {
	*testing.Fake
}

func (c *FakeDirectpvV1beta1) DirectPVDrives() v1beta1.DirectPVDriveInterface {
	return &FakeDirectPVDrives{c}
}

func (c *FakeDirectpvV1beta1) DirectPVInitRequests() v1beta1.DirectPVInitRequestInterface {
	return &FakeDirectPVInitRequests{c}
}

func (c *FakeDirectpvV1beta1) DirectPVNodes() v1beta1.DirectPVNodeInterface {
	return &FakeDirectPVNodes{c}
}

func (c *FakeDirectpvV1beta1) DirectPVVolumes() v1beta1.DirectPVVolumeInterface {
	return &FakeDirectPVVolumes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDirectpvV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
