// This file is part of MinIO DirectPV
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/minio/directpv/pkg/apis/directpv.min.io/v1beta1"
	directpvminiov1beta1 "github.com/minio/directpv/pkg/clientset/typed/directpv.min.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDirectPVNodes implements DirectPVNodeInterface
type fakeDirectPVNodes struct {
	*gentype.FakeClientWithList[*v1beta1.DirectPVNode, *v1beta1.DirectPVNodeList]
	Fake *FakeDirectpvV1beta1
}

func newFakeDirectPVNodes(fake *FakeDirectpvV1beta1) directpvminiov1beta1.DirectPVNodeInterface {
	return &fakeDirectPVNodes{
		gentype.NewFakeClientWithList[*v1beta1.DirectPVNode, *v1beta1.DirectPVNodeList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("directpvnodes"),
			v1beta1.SchemeGroupVersion.WithKind("DirectPVNode"),
			func() *v1beta1.DirectPVNode { return &v1beta1.DirectPVNode{} },
			func() *v1beta1.DirectPVNodeList { return &v1beta1.DirectPVNodeList{} },
			func(dst, src *v1beta1.DirectPVNodeList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.DirectPVNodeList) []*v1beta1.DirectPVNode {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.DirectPVNodeList, items []*v1beta1.DirectPVNode) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
