apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  finalizers:
  - foregroundDeletion
  labels:
    directpv.min.io/version: v1beta1
    pod-security.kubernetes.io/enforce: privileged
  name: directpv
spec: {}
status: {}
