
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    directpv.min.io/created-by: bulk-init
    directpv.min.io/version: v1beta1
  name: directpv-bulk-init
  namespace: directpv
