// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	directcsiminiov1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	versioned "github.com/minio/direct-csi/pkg/clientset/versioned"
	internalinterfaces "github.com/minio/direct-csi/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/minio/direct-csi/pkg/listers/direct.csi.min.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StorageTopologyInformer provides access to a shared informer and lister for
// StorageTopologies.
type StorageTopologyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StorageTopologyLister
}

type storageTopologyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStorageTopologyInformer constructs a new informer for StorageTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStorageTopologyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStorageTopologyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStorageTopologyInformer constructs a new informer for StorageTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStorageTopologyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DirectV1alpha1().StorageTopologies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DirectV1alpha1().StorageTopologies(namespace).Watch(context.TODO(), options)
			},
		},
		&directcsiminiov1alpha1.StorageTopology{},
		resyncPeriod,
		indexers,
	)
}

func (f *storageTopologyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStorageTopologyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *storageTopologyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&directcsiminiov1alpha1.StorageTopology{}, f.defaultInformer)
}

func (f *storageTopologyInformer) Lister() v1alpha1.StorageTopologyLister {
	return v1alpha1.NewStorageTopologyLister(f.Informer().GetIndexer())
}
