name: Testing on k8s v1.23.3 (Ubuntu 18.04)

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
          jq --version

      - name: Set environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          mkdir -p "$(go env GOPATH)/src/github.com/minio/"
          ln -s "$PWD" "$(go env GOPATH)/src/github.com/minio/directpv"
          echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build binaries
        env:
          CGO_ENABLED: 0
          GO111MODULE: on
        run: |
          go build -tags "osusergo netgo static_build" -ldflags="-X main.Version=${VERSION} -extldflags=-static" github.com/minio/directpv/cmd/directpv
          go build -tags "osusergo netgo static_build" -ldflags="-X main.Version=${VERSION} -extldflags=-static" github.com/minio/directpv/cmd/kubectl-direct_csi
          echo "BUILD_TAG=v0.0.0-$(./directpv --version)" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          docker build -t quay.io/minio/directpv:${BUILD_TAG} .

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: 'v1.24.0'
          kubernetes version: 'v1.23.3'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Minikube
        run: |
          kubectl get nodes
          kubectl get pods -A

      - name: Run tests
        run: |
          functests/run.sh ${BUILD_TAG}
