// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/minio/direct-csi/pkg/apis/direct.csi.min.io/v1alpha1"
	scheme "github.com/minio/direct-csi/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageTopologiesGetter has a method to return a StorageTopologyInterface.
// A group's client should implement this interface.
type StorageTopologiesGetter interface {
	StorageTopologies() StorageTopologyInterface
}

// StorageTopologyInterface has methods to work with StorageTopology resources.
type StorageTopologyInterface interface {
	Create(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.CreateOptions) (*v1alpha1.StorageTopology, error)
	Update(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (*v1alpha1.StorageTopology, error)
	UpdateStatus(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (*v1alpha1.StorageTopology, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.StorageTopology, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.StorageTopologyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageTopology, err error)
	StorageTopologyExpansion
}

// storageTopologies implements StorageTopologyInterface
type storageTopologies struct {
	client rest.Interface
}

// newStorageTopologies returns a StorageTopologies
func newStorageTopologies(c *DirectV1alpha1Client) *storageTopologies {
	return &storageTopologies{
		client: c.RESTClient(),
	}
}

// Get takes name of the storageTopology, and returns the corresponding storageTopology object, and an error if there is any.
func (c *storageTopologies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageTopology, err error) {
	result = &v1alpha1.StorageTopology{}
	err = c.client.Get().
		Resource("storagetopologies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageTopologies that match those selectors.
func (c *storageTopologies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageTopologyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StorageTopologyList{}
	err = c.client.Get().
		Resource("storagetopologies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageTopologies.
func (c *storageTopologies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("storagetopologies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a storageTopology and creates it.  Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *storageTopologies) Create(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.CreateOptions) (result *v1alpha1.StorageTopology, err error) {
	result = &v1alpha1.StorageTopology{}
	err = c.client.Post().
		Resource("storagetopologies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageTopology).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a storageTopology and updates it. Returns the server's representation of the storageTopology, and an error, if there is any.
func (c *storageTopologies) Update(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (result *v1alpha1.StorageTopology, err error) {
	result = &v1alpha1.StorageTopology{}
	err = c.client.Put().
		Resource("storagetopologies").
		Name(storageTopology.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageTopology).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *storageTopologies) UpdateStatus(ctx context.Context, storageTopology *v1alpha1.StorageTopology, opts v1.UpdateOptions) (result *v1alpha1.StorageTopology, err error) {
	result = &v1alpha1.StorageTopology{}
	err = c.client.Put().
		Resource("storagetopologies").
		Name(storageTopology.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageTopology).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the storageTopology and deletes it. Returns an error if one occurs.
func (c *storageTopologies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("storagetopologies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageTopologies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("storagetopologies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched storageTopology.
func (c *storageTopologies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageTopology, err error) {
	result = &v1alpha1.StorageTopology{}
	err = c.client.Patch(pt).
		Resource("storagetopologies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
