apiVersion: charts.quay.io/v1alpha1
kind: DirectPVChart
metadata:
  name: directpvchart-sample
spec:
  # Default values copied from <project_dir>/helm-charts/directpv-chart/values.yaml
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
